name: memory_game_flutter
description: Emoji tabanlı hafıza kart eşleştirme oyunu

version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  audioplayers: ^6.5.0
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.5.4
  test: ^1.25.15

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/sounds/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700